matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      dist: trusty
    - os: osx
      python: 2.7

addons:
  apt:
    packages:
      - doxygen
      - cmake
      - gdb

before_install:
  - bash -xe ci/before-install.sh

install:
  - pip install -r requirements.txt --user
  - pip install -e . --user

script:
  # Make sure ssh user@localhost works (for qibuild deploy tests)
  - bash -xe ci/setup-ssh.sh
  - bash -xe ci/setup-git.sh
  - bash -xe ci/run-invoke.sh
